

services:
  gestion-eventos-facyt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestion_eventos_facyt_container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    # Carga las variables de entorno desde el archivo .env (incluyendo GEMINI_API_KEY)
    env_file:
      - .env
    volumes:
      # Este montaje de volumen garantiza que el archivo de la base de datos local (db.json)
      # esté sincronizado entre tu máquina física (host) y el contenedor.
      # Cualquier modificación de los datos se persistirá aquí.
      - ./data:/app/data
    restart: unless-stopped
